### ISSUE TITLE
Problema ao entrar no menu 'Portifolio'

### ISSUE THREAD

**Issue by liomoura** [marcus-sacramento-redmine/redmine_portfolio_management#6]
Primeiramente, parabéns pela iniciativa do plugin. A comunidade carece de um plugin com esta finalidade.

Após realizar a instalação e configuração dos campos customizados, estou me deparando com o erro abaixo colhido no log de produção, ao tentar entrar no menu do topo, 'Portifolio'.

Started GET "/redmine/portfolio_management" for 127.0.0.1 at 2016-04-19 17:40:42 -0300
Processing by PortfolioManagementController#index as HTML
  Current user: admin (id=1)
Mysql2::Error: FUNCTION bitnami_redmine.regexp_replace does not exist: Select distinct cf.id,cv.Value,regexp_replace(lower(cv.Value),'[^a-zA-Z0-9]+','','g') as value_id from custom_values cv,custom_fields cf where cf.id = cv.custom_field_id and cf.type = 'ProjectCustomField' and name = 'Portifolio' and cv.Value <> ''
  Rendered plugins/redmine_portfolio_management/app/views/portfolio_management/index.html.erb within layouts/base (66.4ms)
WARNING: Can't mass-assign protected attributes for AdminMonitorAlert: counter

Desde já, obrigado!

Redmine version 3.1.1

**Comment by MarcuSacramento** [comment]
Obrigado pela ajuda em melhorar o plugin. Será alterado o código para tratar a expressão regular via ruby e não no sql. isso torna o projeto mais portável.

Abraços
